Removed unused code related to BackOtter's line target tracking, to prepare for refactoring. BackOtterTargetTracker.get_line_targets is temporarily retained, as removing it (and thus related code in ClosestToTargetsStrategy) causes the following error in make test (but not make native):
Error: Files src/runotter.d.cmo and src/BackOtter.d.cmo
       make inconsistent assumptions over interface BackOtter